version: '3'
services:
  # Backend Go (with Gin Framework) - Production
  server:
    build:
      context: ./area_back_end/
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    volumes:
      - ${BACKEND_PATH}:/app
      - ./assets:/app/shared-assets
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - GIN_MODE=release

# Frontend Vue.js - Production
  client_web:
    image: node:18.17
    container_name: frontend-prod
    volumes:
      - ${FRONTEND_PATH}:/app
      - ./assets:/app/shared-assets
    ports:
      - "${FRONTEND_PORT}:8081"
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run serve"
    depends_on:
      - server 

  # Mobile React Native - Production
  client_mobile:
    build:
      context: ${MOBILE_PATH}
      dockerfile: Dockerfile.prod
    ports:
      - "${MOBILE_PORT_PROD}:19000"
    environment:
      - NODE_ENV=production
    volumes:
      - ${MOBILE_PATH}:/app
      - ./assets:/app/shared-assets
    depends_on:
      - server
  
  # DB in Postgresql
  db:
    image: postgres:16
    container_name: postgres_container
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
