# Utilisez l'image de base Node.js
FROM node:16

# Définissez le répertoire de travail
WORKDIR /app

# Copiez le package.json et le package-lock.json dans le conteneur
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Installez Expo CLI globalement
RUN npm install -g expo-cli

# Exécutez Expo pour lancer l'application en mode de développement
CMD ["expo", "start"]
